# ?????
spring.datasource.type=com.alibaba.druid.pool.DruidDataSource
spring.datasource.druid.master.driver-class-name=com.mysql.jdbc.Driver
spring.datasource.druid.master.jdbc-url=jdbc:mysql://localhost:23305/news?useUnicode=true&characterEncoding=utf8&nullCatalogMeansCurrent=true&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8
spring.datasource.druid.master.username=root
spring.datasource.druid.master.password=yourpassword

# com.mysql.cj.jdbc.Driver mysql 8+
# com.mysql.jdbc.Driver mysql 5+
spring.datasource.druid.slave.driver-class-name=com.mysql.jdbc.Driver
spring.datasource.druid.slave.jdbc-url=jdbc:mysql://localhost:23305/news?useUnicode=true&characterEncoding=utf8&nullCatalogMeansCurrent=true&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8
spring.datasource.druid.slave.username=root
spring.datasource.druid.slave.password=yourpassword