# 数据库连接
spring.datasource.type=com.alibaba.druid.pool.DruidDataSource
spring.datasource.druid.master.driver-class-name=dm.jdbc.driver.DmDriver
spring.datasource.druid.master.jdbc-url=jdbc:dm://localhost:5236/NEWS
spring.datasource.druid.master.username=SYSDBA
spring.datasource.druid.master.password=u9hJ_1@qqqAAA

spring.datasource.druid.slave.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.druid.slave.jdbc-url=jdbc:mysql://localhost:13306/mall?useUnicode=true&characterEncoding=utf8&nullCatalogMeansCurrent=true&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8
spring.datasource.druid.slave.username=root
spring.datasource.druid.slave.password=8Ui!s1Aj9