# 项目相关配置
# 名称
news.name=news
# 版本
news.version=1.0.0
# 版权年份
news.copyrightYear=2023
news.local-file-path=D:/workspace/local-workspace/news/uploadPath
news.local-file-url=http://localhost:9000
news.new-server-url=http://101.34.59.38
# 获取ip地址开关
news.addressEnabled=true
