# ?????
spring.datasource.type=com.alibaba.druid.pool.DruidDataSource
spring.datasource.druid.master.driver-class-name=dm.jdbc.driver.DmDriver
spring.datasource.druid.master.jdbc-url=jdbc:dm://localhost:5236/NEWS
spring.datasource.druid.master.username=SYSDBA
spring.datasource.druid.master.password=SYSDBA

# com.mysql.cj.jdbc.Driver mysql 8+
# com.mysql.jdbc.Driver mysql 5+
spring.datasource.druid.slave.driver-class-name=com.mysql.jdbc.Driver
spring.datasource.druid.slave.jdbc-url=jdbc:mysql://10.75.37.23:3306/biz_06001026?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
spring.datasource.druid.slave.username=biz_06001026
spring.datasource.druid.slave.password=D)VHDGJ#@!B&