# 数据库连接

#spring.datasource.type=com.alibaba.druid.pool.DruidDataSource
#spring.datasource.druid.driver-class-name=dm.jdbc.driver.DmDriver
#spring.datasource.druid.url=jdbc:dm://localhost:5236/NEWS
#spring.datasource.druid.username=SYSDBA
#spring.datasource.druid.password=SYSDBA