# 登录相关配置

# 验证码
# 验证码类型配置 查看 LoginProperties 类
login.login-code.code-type=arithmetic
# 登录图形验证码有效时间/分钟
login.login-code.expiration=2
# 验证码高度
login.login-code.width=111
# 验证码宽度
login.login-code.heigth=36
# 内容长度
login.login-code.length=2
# 字体名称，为空则使用默认字体
login.login-code.font-name=
# 字体大小
login.login-code.font-size=25

# 失效时间 分钟（在xxx周期内失败次数）
login.lock.failure-expire-time=10
# 失败次数
login.lock.failure-count=5
# 锁定时间 分钟
login.lock.lock-time=30