wechat.columns[0].name=纲举目张-政策放送
wechat.columns[0].type=homepage
wechat.columns[0].sn=b2493920c3c68e84e86da89e4e12d06b

wechat.columns[1].name=纲举目张-绍组动态
wechat.columns[1].type=appmsgalbum
wechat.columns[1].albumId=2506355958886055938

wechat.columns[2].name=纲举目张-窗口之声
wechat.columns[2].type=appmsgalbum
wechat.columns[2].albumId=2506358008675975170

wechat.columns[3].name=撸袖实干-一号工程
wechat.columns[3].type=homepage
wechat.columns[3].sn=4617ad330fa4cdfde4960a9f0eeb7d5b

wechat.columns[4].name=纲举目张-砺剑台
wechat.columns[4].type=appmsgalbum
wechat.columns[4].albumId=2506336560599154689

wechat.columns[5].name=撸袖实干-大抓基层
wechat.columns[5].type=homepage
wechat.columns[5].sn=0e04f82fb1d08a53718f99d6dd1b11f3

wechat.columns[6].name=撸袖实干-名士之乡
wechat.columns[6].type=homepage
wechat.columns[6].sn=25e0a86260f4fc7f7c285ed4e5533a14

wechat.columns[7].name=纲举目张-组工悦读
wechat.columns[7].type=appmsgalbum
wechat.columns[7].albumId=2506331849607233541

wechat.columns[8].name=纲举目张-组工锐评
wechat.columns[8].type=appmsgalbum
wechat.columns[8].albumId=2506335827418038273

wechat.columns[9].name=积跬致远-中心在心中
wechat.columns[9].type=homepage
wechat.columns[9].sn=ee367c08afb98d9f618686ea0dc513df