# 项目相关配置
# 名称
news.name=news
# 版本
news.version=1.0.0
# 版权年份
news.copyrightYear=2023
news.local-file-path=E:/cms/news/uploadPath
news.local-file-url=https://manage.sxdj.gov.cn
news.new-server-url=http://10.75.42.85:8090
# 获取ip地址开关
news.addressEnabled=true
